CLASS LHC_DEMOLEVEL1 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR DemoLevel1
        RESULT result,
      CALCULATESEMANTICKEY1 FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  DemoLevel1~CalculateSemanticKey1 .
ENDCLASS.

CLASS LHC_DEMOLEVEL1 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD CALCULATESEMANTICKEY1.
  ENDMETHOD.
ENDCLASS.
