CLASS LHC_DEMOLEVEL4 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATESEMANTICKEY4 FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  DemoLevel4~CalculateSemanticKey4 .
ENDCLASS.

CLASS LHC_DEMOLEVEL4 IMPLEMENTATION.
  METHOD CALCULATESEMANTICKEY4.
  ENDMETHOD.
ENDCLASS.
