CLASS LHC_DEMOLEVEL3 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATESEMANTICKEY3 FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  DemoLevel3~CalculateSemanticKey3 .
ENDCLASS.

CLASS LHC_DEMOLEVEL3 IMPLEMENTATION.
  METHOD CALCULATESEMANTICKEY3.
  ENDMETHOD.
ENDCLASS.
