CLASS LHC_DEMOLEVEL2 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATESEMANTICKEY2 FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  DemoLevel2~CalculateSemanticKey2 .
ENDCLASS.

CLASS LHC_DEMOLEVEL2 IMPLEMENTATION.
  METHOD CALCULATESEMANTICKEY2.
  ENDMETHOD.
ENDCLASS.
